Header header


string operationMode

float32 currentInclinationRadAvg
float32 currentInclinationDegAvg

float32 currentArmGravityAngleRadAvg
float32 currentArmGravityAngleDegAvg

float32 slipCondition
float32 slipConditionMargin

float32 lambda_F

float32 minTensionV
float32 minTensionKG

float32 referenceTensionV_base
float32 referenceTensionKG_base

float32 activeForceV
float32 activeForceKG

float32 referenceTensionV
float32 referenceTensionKG

float32 measuredTensionV
float32 measuredTensionKG

float32 tensionErrorV
float32 tensionErrorKG

float32 Kp_in
float32 Kp_out

float32 motorVoltCommand_fb

float32 robotLinearVelocity
float32 numSpoolTurns
float32 spoolRadius
float32 armAngleRad

float32 motorVoltCommand_ff

float32 motorVoltCommand
